CREATE TABLE fact_wam_scores (
    time_id                 DATETIME,
    wiki_id                 INTEGER UNSIGNED,
    pageviews_28day         INTEGER UNSIGNED,
    pageviews_7day          INTEGER UNSIGNED,
    edits_28day             INTEGER UNSIGNED,
    edits_7day              INTEGER UNSIGNED,
    editors_28day           INTEGER UNSIGNED,
    editors_7day            INTEGER UNSIGNED,
    pageviews_28_to_15      INTEGER UNSIGNED,
    pageviews_14_to_1       INTEGER UNSIGNED,
    pageviews_8_to_5        INTEGER UNSIGNED,
    pageviews_4_to_1        INTEGER UNSIGNED,
    pageviews_28day_rank    SMALLINT UNSIGNED,
    pageviews_7day_rank     SMALLINT UNSIGNED,
    edits_28day_rank        SMALLINT UNSIGNED,
    edits_7day_rank         SMALLINT UNSIGNED,
    editors_28day_rank      SMALLINT UNSIGNED,
    editors_7day_rank       SMALLINT UNSIGNED,
    growth_14day_rank       SMALLINT UNSIGNED,
    growth_4day_rank        SMALLINT UNSIGNED,
    avg_rank                DECIMAL(9,4),
    wam                     DECIMAL(7,4),
    wam_rank                SMALLINT UNSIGNED,
    PRIMARY KEY (time_id, wiki_id),
    INDEX (wiki_id, time_id)
) ENGINE=InnoDB;

