# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Wikia::Thumbnailer"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

# Wikia-based settings
# - The port server will listen to.
port: 39393

# - The IP address that the server app should bind to. Default is 0.0.0.0
server: 0.0.0.0

# - If set to true, server will display full stack traces when a warning or a die occurs
traces: true

# - log
log_path: "/tmp"
log_file: "thumbnailer.log"
logger: "console"
log: "core"

# should Dancer consider warnings as critical errors?
warnings: 1

# should Dancer show a stacktrace when an error is caught?
show_errors: 1

# - status message
status_msg: "OK"

# - additional config
use_store: true
use_http: true

# http max-age
max_age: 30

# - base path
basepath: "/images"

# - base image url 
baseurl: "http://images.wikia.com"

# - max width of image
maxwidth: 3000 

# - max image zoom (for video)
maxzoom: 1080

# - max zoom ration (for video)
maxzoomratio: 3

# - default background color 
background: "FFFFFF"

# - http proxy
lwp_proxy: ""

#- LWP timeout
lwp_timeout: 20

#- jpeg quality
jpegquality: 95

#- svg default parameters
svg_ratio: 1.0
svg_def_width: 512
svg_def_height: 512

# - video thumb creator
video_thumb: "/usr/bin/oggThumb"
video_tmp_dir: "/tmp"
video_thumb_params: "-o jpg -f0 -t%d %s"
video_thumb_result_parse: "writing (.+)"

# mimetype 
image_mimetype:
 image/jpeg: jpeg
 image/png: png
 image/gif: gif
 image/tiff: tiff
 image/x-ms-bmp: bmp
 image/x-bmp: bmp
 image/svg+xml: png
 image/svg: png
 image/x-icon: ico

# image scale 
scale: 
 default: 5
 max: 10
