/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PhalanxStats extends org.jooq.impl.TableImpl<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord> {

	private static final long serialVersionUID = 1332760770;

	/**
	 * The singleton instance of phalanx.phalanx_stats
	 */
	public static final com.wikia.phalanx.db.tables.PhalanxStats PHALANX_STATS = new com.wikia.phalanx.db.tables.PhalanxStats();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord> getRecordType() {
		return com.wikia.phalanx.db.tables.records.PhalanxStatsRecord.class;
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_id</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord, org.jooq.tools.unsigned.UInteger> PS_BLOCKER_ID = createField("ps_blocker_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_type</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord, org.jooq.tools.unsigned.UShort> PS_BLOCKER_TYPE = createField("ps_blocker_type", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_timestamp</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord, byte[]> PS_TIMESTAMP = createField("ps_timestamp", org.jooq.impl.SQLDataType.BINARY, this);

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocked_user</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord, java.lang.String> PS_BLOCKED_USER = createField("ps_blocked_user", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_wiki_id</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord, java.lang.Integer> PS_WIKI_ID = createField("ps_wiki_id", org.jooq.impl.SQLDataType.INTEGER, this);

	public PhalanxStats() {
		super("phalanx_stats", com.wikia.phalanx.db.Phalanx.PHALANX);
	}

	public PhalanxStats(java.lang.String alias) {
		super(alias, com.wikia.phalanx.db.Phalanx.PHALANX, com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS);
	}

	@Override
	public com.wikia.phalanx.db.tables.PhalanxStats as(java.lang.String alias) {
		return new com.wikia.phalanx.db.tables.PhalanxStats(alias);
	}
}
