/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Phalanx extends org.jooq.impl.UpdatableTableImpl<com.wikia.phalanx.db.tables.records.PhalanxRecord> {

	private static final long serialVersionUID = -183544978;

	/**
	 * The singleton instance of phalanx.phalanx
	 */
	public static final com.wikia.phalanx.db.tables.Phalanx PHALANX = new com.wikia.phalanx.db.tables.Phalanx();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.wikia.phalanx.db.tables.records.PhalanxRecord> getRecordType() {
		return com.wikia.phalanx.db.tables.records.PhalanxRecord.class;
	}

	/**
	 * The table column <code>phalanx.phalanx.p_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, org.jooq.tools.unsigned.UInteger> P_ID = createField("p_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this);

	/**
	 * The table column <code>phalanx.phalanx.p_author_id</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.Integer> P_AUTHOR_ID = createField("p_author_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>phalanx.phalanx.p_text</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, byte[]> P_TEXT = createField("p_text", org.jooq.impl.SQLDataType.BLOB, this);

	/**
	 * The table column <code>phalanx.phalanx.p_ip_hex</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.String> P_IP_HEX = createField("p_ip_hex", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>phalanx.phalanx.p_type</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, org.jooq.tools.unsigned.UShort> P_TYPE = createField("p_type", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this);

	/**
	 * The table column <code>phalanx.phalanx.p_timestamp</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, byte[]> P_TIMESTAMP = createField("p_timestamp", org.jooq.impl.SQLDataType.BINARY, this);

	/**
	 * The table column <code>phalanx.phalanx.p_expire</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, byte[]> P_EXPIRE = createField("p_expire", org.jooq.impl.SQLDataType.BINARY, this);

	/**
	 * The table column <code>phalanx.phalanx.p_exact</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.Byte> P_EXACT = createField("p_exact", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>phalanx.phalanx.p_regex</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.Byte> P_REGEX = createField("p_regex", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>phalanx.phalanx.p_case</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.Byte> P_CASE = createField("p_case", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>phalanx.phalanx.p_reason</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, byte[]> P_REASON = createField("p_reason", org.jooq.impl.SQLDataType.BLOB, this);

	/**
	 * The table column <code>phalanx.phalanx.p_lang</code>
	 */
	public final org.jooq.TableField<com.wikia.phalanx.db.tables.records.PhalanxRecord, java.lang.String> P_LANG = createField("p_lang", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Phalanx() {
		super("phalanx", com.wikia.phalanx.db.Phalanx.PHALANX);
	}

	public Phalanx(java.lang.String alias) {
		super(alias, com.wikia.phalanx.db.Phalanx.PHALANX, com.wikia.phalanx.db.tables.Phalanx.PHALANX);
	}

	@Override
	public org.jooq.Identity<com.wikia.phalanx.db.tables.records.PhalanxRecord, org.jooq.tools.unsigned.UInteger> getIdentity() {
		return com.wikia.phalanx.db.Keys.IDENTITY_PHALANX;
	}

	@Override
	public org.jooq.UniqueKey<com.wikia.phalanx.db.tables.records.PhalanxRecord> getMainKey() {
		return com.wikia.phalanx.db.Keys.KEY_PHALANX_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<com.wikia.phalanx.db.tables.records.PhalanxRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.wikia.phalanx.db.tables.records.PhalanxRecord>>asList(com.wikia.phalanx.db.Keys.KEY_PHALANX_PRIMARY);
	}

	@Override
	public com.wikia.phalanx.db.tables.Phalanx as(java.lang.String alias) {
		return new com.wikia.phalanx.db.tables.Phalanx(alias);
	}
}
