DROP TABLE IF EXISTS statsdb.lookup_search_domains;

CREATE TABLE statsdb.lookup_search_domains (
    search_domain_id    SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    search_domain       VARCHAR(255),
    description         VARCHAR(255),
    PRIMARY KEY (search_domain_id),
    INDEX lookup_search_domain (search_domain)
) ENGINE=InnoDB;

-- Data sourced from: http://cpansearch.perl.org/src/SDEN/URI-ParseSearchString-3.442/lib/URI/ParseSearchString.pm

INSERT INTO statsdb.lookup_search_domains (search_domain_id, search_domain, description) VALUES
    (1, 'abacho.com', 'Abacho'),
    (2, 'acbusca.com', 'ACBusca'),
    (3, 'aeiou.pt', 'Aeiou'),
    (4, 'alice.it', 'Alice.it'),
    (5, 'alltheweb.com', 'AllTheWeb'),
    (6, 'altavista.com', 'Altavista'),
    (7, 'answers.yahoo.com', 'Yahoo Answers'),
    (8, 'aolsearch.aol.com', 'AOL Search'),
    (9, 'ask.com', 'Ask dot com'),
    (10, 'as.starware.com', 'Starware'),
    (11, 'atalhocerto.com.br', 'Atalho Certo'),
    (12, 'bastaclicar.com.br', 'Basta Clicar'),
    (13, 'bemrapido.com.br', 'Bem Rapido'),
    (14, 'bing.com', 'Bing'),
    (15, 'blogsearch.google.com', 'Google Blogsearch'),
    (16, 'blogs.icerocket.com', 'IceRocket'),
    (17, 'blueyonder.co.uk', 'Blueyonder'),
    (18, 'br.altavista.com', 'AltaVista Brasil'),
    (19, 'br.search.yahoo.com', 'Yahoo Brazil'),
    (20, 'buscaaqui.com.br', 'Busca Aqui'),
    (21, 'buscador.lycos.es', 'Lycos ES'),
    (22, 'buscador.terra.com.br', 'Terra Busca'),
    (23, 'buscador.terra.es', 'Terra ES'),
    (24, 'busca.orange.es', 'Orange ES'),
    (25, 'buscar.ozu.es', 'Ozu ES'),
    (26, 'busca.uol.com.br', 'Radar UOL'),
    (27, 'cade.search.yahoo.com', 'CadÃª'),
    (28, 'categorico.it', 'Categorico IT'),
    (29, 'clickgratis.com.br', 'Click Gratis'),
    (30, 'clusty.com', 'Clusty'),
    (31, 'community.paglo.com', 'Paglo'),
    (32, 'correiodamanha.pt', 'Correio da Manha'),
    (33, 'correiomanha.pt', 'Correio Manha'),
    (34, 'cuil.com', 'Cuil'),
    (35, 'cuil.pt', 'Cuil PT'),
    (36, 'dn.sapo.pt', 'Diario Noticias'),
    (37, 'entrada.com.br', 'Entrada'),
    (38, 'excite.com', 'Excite'),
    (39, 'excite.it', 'Excite IT'),
    (40, 'fastbrowsersearch.com', 'Fastbrowsersearch'),
    (41, 'fastweb.it', 'Fastweb IT'),
    (42, 'feedster.com', 'Feedster'),
    (43, 'fotos.sapo.pt', 'SAPO fotos'),
    (44, 'gigabusca.com.br', 'Giga Busca'),
    (45, 'godado.com', 'Godado'),
    (46, 'godado.it', 'Godado (IT)'),
    (47, 'google.ad', 'Google Andorra'),
    (48, 'google.ae', 'Google United Arab Emirates'),
    (49, 'google.af', 'Google Afghanistan'),
    (50, 'google.ag', 'Google Antiqua and Barbuda'),
    (51, 'google.am', 'Google Armenia'),
    (52, 'google.as', 'Google American Samoa'),
    (53, 'google.at', 'Google Austria'),
    (54, 'google.az', 'Google Azerbaijan'),
    (55, 'google.ba', 'Google Bosnia and Herzegovina'),
    (56, 'google.be', 'Google Belgium'),
    (57, 'google.bg', 'Google Bulgaria'),
    (58, 'google.bi', 'Google Burundi'),
    (59, 'google.biz', 'Google dot biz'),
    (60, 'google.bo', 'Google Bolivia'),
    (61, 'google.bs', 'Google Bahamas'),
    (62, 'google.bz', 'Google Belize'),
    (63, 'google.ca', 'Google Canada'),
    (64, 'google.cc', 'Google Cocos Islands'),
    (65, 'google.cd', 'Google Dem Rep of Congo'),
    (66, 'google.cg', 'Google Rep of Congo'),
    (67, 'google.ch', 'Google Switzerland'),
    (68, 'google.ci', 'Google Cote dIvoire'),
    (69, 'google.cl', 'Google Chile'),
    (70, 'google.cn', 'Google China'),
    (71, 'google.co.at', 'Google Austria'),
    (72, 'google.co.bi', 'Google Burundi'),
    (73, 'google.co.bw', 'Google Botswana'),
    (74, 'google.co.ci', 'Google Ivory Coast'),
    (75, 'google.co.ck', 'Google Cook Islands'),
    (76, 'google.co.cr', 'Google Costa Rica'),
    (77, 'google.co.gg', 'Google Guernsey'),
    (78, 'google.co.gl', 'Google Greenland'),
    (79, 'google.co.gy', 'Google Guyana'),
    (80, 'google.co.hu', 'Google Hungary'),
    (81, 'google.co.id', 'Google Indonesia'),
    (82, 'google.co.il', 'Google Israel'),
    (83, 'google.co.im', 'Google Isle of Man'),
    (84, 'google.co.in', 'Google India'),
    (85, 'google.co.it', 'Google Italy'),
    (86, 'google.co.je', 'Google Jersey'),
    (87, 'google.co.jp', 'Google Japan'),
    (88, 'google.co.ke', 'Google Kenya'),
    (89, 'google.co.kr', 'Google South Korea'),
    (90, 'google.co.ls', 'Google Lesotho'),
    (91, 'google.com.af', 'Google Afghanistan'),
    (92, 'google.com.ag', 'Google Antiqua and Barbuda'),
    (93, 'google.co.ma', 'Google Morocco'),
    (94, 'google.com.ai', 'Google Anguilla'),
    (95, 'google.com.ar', 'Google Argentina'),
    (96, 'google.com.au', 'Google Australia'),
    (97, 'google.com.az', 'Google Azerbaijan'),
    (98, 'google.com.bd', 'Google Bangladesh'),
    (99, 'google.com.bh', 'Google Bahrain'),
    (100, 'google.com.bi', 'Google Burundi'),
    (101, 'google.com.bn', 'Google Brunei Darussalam'),
    (102, 'google.com.bo', 'Google Bolivia'),
    (103, 'google.com.br', 'Google Brazil'),
    (104, 'google.com.bs', 'Google Bahamas'),
    (105, 'google.com.bz', 'Google Belize'),
    (106, 'google.com.cn', 'Google China'),
    (107, 'google.com.co', 'Google'),
    (108, 'google.com.cu', 'Google Cuba'),
    (109, 'google.com.do', 'Google Dominican Rep'),
    (110, 'google.com.ec', 'Google Ecuador'),
    (111, 'google.com.eg', 'Google Egypt'),
    (112, 'google.com.et', 'Google Ethiopia'),
    (113, 'google.com.fj', 'Google Fiji'),
    (114, 'google.com.ge', 'Google Georgia'),
    (115, 'google.com.gh', 'Google Ghana'),
    (116, 'google.com.gi', 'Google Gibraltar'),
    (117, 'google.com.gl', 'Google Greenland'),
    (118, 'google.com', 'Google'),
    (119, 'google.com.gp', 'Google Guadeloupe'),
    (120, 'google.com.gr', 'Google Greece'),
    (121, 'google.com.gt', 'Google Guatemala'),
    (122, 'google.com.gy', 'Google Guyana'),
    (123, 'google.com.hk', 'Google Hong Kong'),
    (124, 'google.com.hn', 'Google Honduras'),
    (125, 'google.com.hr', 'Google Croatia'),
    (126, 'google.com.jm', 'Google Jamaica'),
    (127, 'google.com.jo', 'Google Jordan'),
    (128, 'google.com.kg', 'Google Kyrgyzstan'),
    (129, 'google.com.kh', 'Google Cambodia'),
    (130, 'google.com.ki', 'Google Kiribati'),
    (131, 'google.com.kz', 'Google Kazakhstan'),
    (132, 'google.com.lk', 'Google Sri Lanka'),
    (133, 'google.com.lv', 'Google Latvia'),
    (134, 'google.com.ly', 'Google Libya'),
    (135, 'google.com.mt', 'Google Malta'),
    (136, 'google.com.mu', 'Google Mauritius'),
    (137, 'google.com.mw', 'Google Malawi'),
    (138, 'google.com.mx', 'Google Mexico'),
    (139, 'google.com.my', 'Google Malaysia'),
    (140, 'google.com.na', 'Google Namibia'),
    (141, 'google.com.nf', 'Google Norfolk Island'),
    (142, 'google.com.ng', 'Google Nigeria'),
    (143, 'google.com.ni', 'Google Nicaragua'),
    (144, 'google.com.np', 'Google Nepal'),
    (145, 'google.com.nr', 'Google Nauru'),
    (146, 'google.com.om', 'Google Oman'),
    (147, 'google.com.pa', 'Google Panama'),
    (148, 'google.com.pe', 'Google Peru'),
    (149, 'google.com.ph', 'Google Philipines'),
    (150, 'google.com.pk', 'Google Pakistan'),
    (151, 'google.com.pl', 'Google Poland'),
    (152, 'google.com.pr', 'Google Puerto Rico'),
    (153, 'google.com.pt', 'Google Portugal'),
    (154, 'google.com.py', 'Google Paraguay'),
    (155, 'google.com.qa', 'Google'),
    (156, 'google.com.ru', 'Google Russia'),
    (157, 'google.com.sa', 'Google Saudi Arabia'),
    (158, 'google.com.sb', 'Google Solomon Islands'),
    (159, 'google.com.sc', 'Google Seychelles'),
    (160, 'google.com.sg', 'Google Singapore'),
    (161, 'google.com.sv', 'Google El Savador'),
    (162, 'google.com.tj', 'Google Tajikistan'),
    (163, 'google.com.tr', 'Google Turkey'),
    (164, 'google.com.tt', 'Google Trinidad and Tobago'),
    (165, 'google.com.tw', 'Google Taiwan'),
    (166, 'google.com.ua', 'Google Ukraine'),
    (167, 'google.co.mu', 'Google Mauritius'),
    (168, 'google.com.uy', 'Google Uruguay'),
    (169, 'google.com.uz', 'Google Uzbekistan'),
    (170, 'google.com.ve', 'Google Venezuela'),
    (171, 'google.com.vi', 'Google US Virgin Islands'),
    (172, 'google.com.vn', 'Google Vietnam'),
    (173, 'google.co.mw', 'Google Malawi'),
    (174, 'google.com.ws', 'Google Samoa'),
    (175, 'google.co.nz', 'Google New Zeland'),
    (176, 'google.co.pn', 'Google Pitcairn Islands'),
    (177, 'google.co.th', 'Google Thailand'),
    (178, 'google.co.tt', 'Google Trinidad and Tobago'),
    (179, 'google.co.ug', 'Google Uganda'),
    (180, 'google.co.uk', 'Google UK'),
    (181, 'google.co.uz', 'Google Uzbekistan'),
    (182, 'google.co.ve', 'Google Venezuela'),
    (183, 'google.co.vi', 'Google US Virgin Islands'),
    (184, 'google.co.za', 'Google  South Africa'),
    (185, 'google.co.zm', 'Google Zambia'),
    (186, 'google.co.zw', 'Google Zimbabwe'),
    (187, 'google.cz', 'Google Czech Rep'),
    (188, 'google.de', 'Google Germany'),
    (189, 'google.dj', 'Google Djubouti'),
    (190, 'google.dk', 'Google Denmark'),
    (191, 'google.dm', 'Google Dominica'),
    (192, 'google.ec', 'Google Ecuador'),
    (193, 'google.ee', 'Google Estonia'),
    (194, 'google.es', 'Google Spain'),
    (195, 'google.fi', 'Google Finland'),
    (196, 'google.fm', 'Google Micronesia'),
    (197, 'google.fr', 'Google France'),
    (198, 'google.gd', 'Google Grenada'),
    (199, 'google.ge', 'Google Georgia'),
    (200, 'google.gf', 'Google French Guiana'),
    (201, 'google.gg', 'Google Guernsey'),
    (202, 'google.gl', 'Google Greenland'),
    (203, 'google.gm', 'Google Gambia'),
    (204, 'google.gp', 'Google Guadeloupe'),
    (205, 'google.gr', 'Google Greece'),
    (206, 'google.gy', 'Google Guyana'),
    (207, 'google.hk', 'Google Hong Kong'),
    (208, 'google.hn', 'Google Honduras'),
    (209, 'google.hr', 'Google Croatia'),
    (210, 'google.ht', 'Google Haiti'),
    (211, 'google.hu', 'Google Hungary'),
    (212, 'google.ie', 'Google Ireland'),
    (213, 'google.im', 'Google Isle of Man'),
    (214, 'google.info', 'Google dot info'),
    (215, 'google.in', 'Google India'),
    (216, 'google.is', 'Google Iceland'),
    (217, 'google.it', 'Google Italy'),
    (218, 'google.je', 'Google Jersey'),
    (219, 'google.jobs', 'Google dot jobs'),
    (220, 'google.jo', 'Google Jordan'),
    (221, 'google.jp', 'Google Japan'),
    (222, 'google.kg', 'Google Kyrgyzstan'),
    (223, 'google.ki', 'Google Kiribati'),
    (224, 'google.kz', 'Google Kazakhstan'),
    (225, 'google.la', 'Google Laos'),
    (226, 'google.li', 'Google Liechtenstein'),
    (227, 'google.lk', 'Google Sri Lanka'),
    (228, 'google.lt', 'Google Lithuania'),
    (229, 'google.lu', 'Google Luxembourg'),
    (230, 'google.lv', 'Google Latvia'),
    (231, 'google.ma', 'Google Morocco'),
    (232, 'google.md', 'Google Moldova'),
    (233, 'google.mn', 'Google Mongolia'),
    (234, 'google.mobi', 'Google dot mobi'),
    (235, 'google.ms', 'Google Montserrat'),
    (236, 'google.mu', 'Google Mauritius'),
    (237, 'google.mv', 'Google Maldives'),
    (238, 'google.mw', 'Google Malawi'),
    (239, 'google.net', 'Google dot net'),
    (240, 'google.nf', 'Google Norfolk Island'),
    (241, 'google.nl', 'Google Netherlands'),
    (242, 'google.no', 'Google Norway'),
    (243, 'google.nr', 'Google Nauru'),
    (244, 'google.nu', 'Google Niue'),
    (245, 'google.off.ai', 'Google Anguilla'),
    (246, 'google.ph', 'Google Philipines'),
    (247, 'google.pk', 'Google Pakistan'),
    (248, 'google.pl', 'Google Poland'),
    (249, 'google.pn', 'Google Pitcairn Islands'),
    (250, 'google.pr', 'Google Puerto Rico'),
    (251, 'google.pt', 'Google Portugal'),
    (252, 'google.ro', 'Google Romania'),
    (253, 'google.ru', 'Google Russia'),
    (254, 'google.rw', 'Google Rwanda'),
    (255, 'google.sc', 'Google Seychelles'),
    (256, 'google.se', 'Google Sweden'),
    (257, 'google.sg', 'Google Singapore'),
    (258, 'google.sh', 'Google Saint Helena'),
    (259, 'google.si', 'Google Slovenia'),
    (260, 'google.sk', 'Google Slovakia'),
    (261, 'google.sm', 'Google San Marino'),
    (262, 'google.sn', 'Google Senegal'),
    (263, 'google.sr', 'Google Suriname'),
    (264, 'google.st', 'Google Sao Tome'),
    (265, 'google.tk', 'Google Tokelau'),
    (266, 'google.tm', 'Google Turkmenistan'),
    (267, 'google.to', 'Google Tonga'),
    (268, 'google.tp', 'Google East Timor'),
    (269, 'google.tt', 'Google Trinidad and Tobago'),
    (270, 'google.tv', 'Google Tuvalu'),
    (271, 'google.tw', 'Google Taiwan'),
    (272, 'google.ug', 'Google Uganda'),
    (273, 'google.us', 'Google US'),
    (274, 'google.uz', 'Google Uzbekistan'),
    (275, 'google.vg', 'Google British Virgin Islands'),
    (276, 'google.vn', 'Google Vietnam'),
    (277, 'google.vu', 'Google Vanuatu'),
    (278, 'google.ws', 'Google Samoa'),
    (279, 'gps.virgin.net', 'Virgin Search'),
    (280, 'guruji.com', 'Guruji'),
    (281, 'hotbot.com', 'HotBot'),
    (282, 'ilmotore.com', 'ilMotore'),
    (283, 'in.gr', 'In GR'),
    (284, 'in.search.yahoo.com', 'Yahoo India'),
    (285, 'internetica.com.br', 'Internetica'),
    (286, 'iol.pt', 'Pesquisa Iol'),
    (287, 'ithaki.net', 'Ithaki'),
    (288, 'jn.sapo.pt', 'Jornal Noticias'),
    (289, 'katatudo.com.br', 'KataTudo'),
    (290, 'kataweb.it', 'Kataweb IT'),
    (291, 'libero.it', 'Libero IT'),
    (292, 'lycos.it', 'Lycos IT'),
    (293, 'mahalo.com', 'Mahalo'),
    (294, 'mamma.com', 'Mamma'),
    (295, 'megasearching.net', 'Megasearching'),
    (296, 'minasplanet.com.br', 'Minas Planet'),
    (297, 'mirago.co.uk', 'Mirago UK'),
    (298, 'netscape.com', 'Netscape'),
    (299, 'pathfinder.gr', 'Pathfinder GR'),
    (300, 'pesquisa.clix.pt', 'Pesquisa Clix'),
    (301, 'phantis.com', 'Phantis GR'),
    (302, 'publico.clix.pt', 'Publico'),
    (303, 'record.pt', 'Jornal Record'),
    (304, 'rediff.com', 'Rediff'),
    (305, 'robby.gr', 'Robby GR'),
    (306, 'rtp.pt', 'Rtp'),
    (307, 'sabores.sapo.pt', 'SAPO sabores'),
    (308, 'sapo.pt', 'Pesquisa SAPO'),
    (309, 'search.aol.co.uk', 'AOL UK'),
    (310, 'search.arabia.msn.com', 'MSN Arabia'),
    (311, 'search.bbc.co.uk', 'BBC Search'),
    (312, 'search.conduit.com', 'Conduit'),
    (313, 'search.conduit.com', 'Conduit'),
    (314, 'search.icq.com', 'ICQ dot com'),
    (315, 'search.live.com', 'Live.com'),
    (316, 'search.lycos.com', 'Lycos'),
    (317, 'search.lycos.co.uk', 'Lycos UK'),
    (318, 'search.msn.com', 'MSN'),
    (319, 'search.msn.co.uk', 'MSN UK'),
    (320, 'search.myway.com', 'MyWay'),
    (321, 'search.mywebsearch.com', 'My Web Search'),
    (322, 'search.ntlworld.com', 'NTLWorld'),
    (323, 'search.orange.co.uk', 'Orange Search'),
    (324, 'search.prodigy.msn.com', 'MSN Prodigy'),
    (325, 'search.sweetim.com', 'Sweetim'),
    (326, 'search.virginmedia.com', 'VirginMedia'),
    (327, 'search.yahoo.co.jp', 'Yahoo Japan'),
    (328, 'search.yahoo.com', 'Yahoo!'),
    (329, 'search.yahoo.jp', 'Yahoo! Japan'),
    (330, 'simpatico.ws', 'Simpatico IT'),
    (331, 'soso.com', 'Soso'),
    (332, 'speedybusca.com.br', 'SpeedyBusca'),
    (333, 'sproose.com', 'Sproose'),
    (334, 'suche.fireball.de', 'Fireball DE'),
    (335, 'suche.t-online.de', 'T-Online'),
    (336, 'suche.web.de', 'Suche DE'),
    (337, 'technorati.com', 'Technorati'),
    (338, 'tesco.net', 'Tesco Search'),
    (339, 'thespider.it', 'TheSpider IT'),
    (340, 'tiscali.co.uk', 'Tiscali UK'),
    (341, 'uk.altavista.com', 'Altavista UK'),
    (342, 'uk.ask.com', 'Ask UK'),
    (343, 'uk.search.yahoo.com', 'Yahoo! UK'),
    (344, 'vaibuscar.com.br', 'Vai Busca'),
    (345, 'videos.sapo.pt', 'SAPO videos'),
    (346, 'xl.pt', 'XL')
;

COMMIT;

