DROP TABLE IF EXISTS statsdb.lookup_browser_languages;

CREATE TABLE statsdb.lookup_browser_languages (
    language_code         VARCHAR(8) NOT NULL,
    language_name         VARCHAR(255),
    language_group        VARCHAR(8),
    language_group_name   VARCHAR(255),
    PRIMARY KEY (language_code),
    UNIQUE KEY (language_name)
) ENGINE=InnoDB;

INSERT INTO statsdb.lookup_browser_languages VALUES 
    ('aa',            'aa',                           'unknown',        'unknown'),
    ('ace',           'ace',                          'unknown',        'unknown'),
    ('af',            'Afrikaans',                    'af',             'Afrikaans'),
    ('ak',            'ak',                           'unknown',        'unknown'),
    ('aln',           'aln',                          'unknown',        'unknown'),
    ('am',            'am',                           'unknown',        'unknown'),
    ('an',            'an',                           'unknown',        'unknown'),
    ('ang',           'ang',                          'unknown',        'unknown'),
    ('ar-ae',         'Arabic (U.A.E.)',              'ar',             'Arabic'),
    ('ar',            'Arabic',                       'ar',             'Arabic'),
    ('ar-bh',         'Arabic (Bahrain)',             'ar',             'Arabic'),
    ('arc',           'arc',                          'unknown',        'unknown'),
    ('ar-dz',         'Arabic (Algeria)',             'ar',             'Arabic'),
    ('ar-eg',         'Arabic (Egypt)',               'ar',             'Arabic'),
    ('ar-iq',         'Arabic (Iraq)',                'ar',             'Arabic'),
    ('ar-jo',         'Arabic (Jordan)',              'ar',             'Arabic'),
    ('ar-kw',         'Arabic (Kuwait)',              'ar',             'Arabic'),
    ('ar-lb',         'Arabic (Lebanon)',             'ar',             'Arabic'),
    ('ar-ly',         'Arabic (Libya)',               'ar',             'Arabic'),
    ('ar-ma',         'Arabic (Morocco)',             'ar',             'Arabic'),
    ('ar-om',         'Arabic (Oman)',                'ar',             'Arabic'),
    ('ar-qa',         'Arabic (Qatar)',               'ar',             'Arabic'),
    ('ar-sa',         'Arabic (Saudi Arabia)',        'ar',             'Arabic'),
    ('ar-sy',         'Arabic (Syria)',               'ar',             'Arabic'),
    ('ar-tn',         'Arabic (Tunisia)',             'ar',             'Arabic'),
    ('ar-ye',         'Arabic (Yemen)',               'ar',             'Arabic'),
    ('arz',           'arz',                          'unknown',        'unknown'),
    ('as',            'Assamese',                     'as',             'Assamese'),
    ('ast',           'Asturian',                     'ast',            'Asturian'),
    ('<autocre',      '<autocre',                     'unknown',        'unknown'),
    ('av',            'av',                           'unknown',        'unknown'),
    ('avk',           'avk',                          'unknown',        'unknown'),
    ('ay',            'ay',                           'unknown',        'unknown'),
    ('az',            'Azerbaijani',                  'az',             'Azerbaijani'),
    ('bat-smg',       'bat-smg',                      'unknown',        'unknown'),
    ('bcc',           'bcc',                          'unknown',        'unknown'),
    ('be',            'Belarusian',                   'be',             'Belarusian'),
    ('be-taras',      'be-taras',                     'unknown',        'unknown'),
    ('be-x-old',      'be-x-old',                     'unknown',        'unknown'),
    ('bg',            'Bulgarian',                    'bg',             'Bulgarian'),
    ('bi',            'bi',                           'unknown',        'unknown'),
    ('bm',            'bm',                           'unknown',        'unknown'),
    ('bn',            'Bengali',                      'bn',             'Bengali'),
    ('bqi',           'bqi',                          'unknown',        'unknown'),
    ('br',            'Breton',                       'br',             'Breton'),
    ('bs',            'Bosnian',                      'bs',             'Bosnian'),
    ('ca',            'Catalan',                      'ca',             'Catalan'),
    ('ceb',           'ceb',                          'unknown',        'unknown'),
    ('ce',            'Chechen',                      'ce',             'Chechen'),
    ('ch',            'Chamorro',                     'ch',             'Chamorro'),
    ('chy',           'chy',                          'unknown',        'unknown'),
    ('co',            'Corsican',                     'co',             'Corsican'),
    ('cr',            'Cree',                         'cr',             'Cree'),
    ('csb',           'csb',                          'unknown',        'unknown'),
    ('cs',            'Czech',                        'cs',             'Czech'),
    ('cv',            'Chuvash',                      'cv',             'Chuvash'),
    ('cy',            'Welsh',                        'cy',             'Welsh'),
    ('da',            'Danish',                       'da',             'Danish'),
    ('de2',           'de2',                          'unknown',        'unknown'),
    ('de-at',         'German (Austria)',             'de',             'German'),
    ('de-ch',         'German (Switzerland)',         'de',             'German'),
    ('de-de',         'German (Germany)',             'de',             'German'),
    ('de',            'German',                       'de',             'German'),
    ('de-li',         'German (Liechtenstein)',       'de',             'German'),
    ('de-lu',         'German (Luxembourg)',          'de',             'German'),
    ('diq',           'diq',                          'unknown',        'unknown'),
    ('dv',            'dv',                           'unknown',        'unknown'),
    ('el',            'Greek',                        'el',             'Greek'),
    ('eml',           'eml',                          'unknown',        'unknown'),
    ('en-au',         'English (Australia)',          'en',             'English'),
    ('en-bz',         'English (Belize)',             'en',             'English'),
    ('en-ca',         'English (Canada)',             'en',             'English'),
    ('en',            'English',                      'en',             'English'),
    ('en-gb',         'English (United Kingdom)',     'en',             'English'),
    ('en-ie',         'English (Ireland)',            'en',             'English'),
    ('en-jm',         'English (Jamaica)',            'en',             'English'),
    ('en-nz',         'English (New Zealand)',        'en',             'English'),
    ('en-ph',         'English (Philippines)',        'en',             'English'),
    ('en-tt',         'English (Trinidad & Tobago)',  'en',             'English'),
    ('en-us',         'English (United States)',      'en',             'English'),
    ('en-za',         'English (South Africa)',       'en',             'English'),
    ('en-zw',         'English (Zimbabwe)',           'en',             'English'),
    ('eo',            'Esperanto',                    'eo',             'Esperanto'),
    ('es-ar',         'Spanish (Argentina)',          'es',             'Spanish'),
    ('es-bo',         'Spanish (Bolivia)',            'es',             'Spanish'),
    ('es-cl',         'Spanish (Chile)',              'es',             'Spanish'),
    ('es-co',         'Spanish (Colombia)',           'es',             'Spanish'),
    ('es-cr',         'Spanish (Costa Rica)',         'es',             'Spanish'),
    ('es-do',         'Spanish (Dominican Republic)', 'es',             'Spanish'),
    ('es-ec',         'Spanish (Ecuador)',            'es',             'Spanish'),
    ('es-es',         'Spanish (Spain)',              'es',             'Spanish'),
    ('es-gt',         'Spanish (Guatemala)',          'es',             'Spanish'),
    ('es-hn',         'Spanish (Honduras)',           'es',             'Spanish'),
    ('es-mx',         'Spanish (Mexico)',             'es',             'Spanish'),
    ('es-ni',         'Spanish (Nicaragua)',          'es',             'Spanish'),
    ('es-pa',         'Spanish (Panama)',             'es',             'Spanish'),
    ('es-pe',         'Spanish (Peru)',               'es',             'Spanish'),
    ('es-pr',         'Spanish (Puerto Rico)',        'es',             'Spanish'),
    ('es-py',         'Spanish (Paraguay)',           'es',             'Spanish'),
    ('es',            'Spanish',                      'es',             'Spanish'),
    ('es-sv',         'Spanish (El Salvador)',        'es',             'Spanish'),
    ('es-uy',         'Spanish (Uruguay)',            'es',             'Spanish'),
    ('es-ve',         'Spanish (Venezuela)',          'es',             'Spanish'),
    ('et',            'Estonian',                     'et',             'Estonian'),
    ('eu',            'Basque',                       'eu',             'Basque'),
    ('fa-ir',         'Persian/Iran',                 'fa',             'Persian'),
    ('fa',            'Persian',                      'fa',             'Persian'),
    ('fi',            'Finnish',                      'fi',             'Finnish'),
    ('fiu-vro',       'fiu-vro',                      'unknown',        'unknown'),
    ('fj',            'Fijian',                       'fj',             'Fijian'),
    ('fo',            'Faeroese',                     'fo',             'Faeroese'),
    ('fr-be',         'French (Belgium)',             'fr',             'French'),
    ('fr-ca',         'French (Canada)',              'fr',             'French'),
    ('fr-ch',         'French (Switzerland)',         'fr',             'French'),
    ('fr',            'French',                       'fr',             'French'),
    ('fr-fr',         'French (France)',              'fr',             'French'),
    ('fr-lu',         'French (Luxembourg)',          'fr',             'French'),
    ('fr-mc',         'French (Monaco)',              'fr',             'French'),
    ('frr',           'frr',                          'unknown',        'unknown'),
    ('fur',           'Friulian',                     'fur',            'Friulian'),
    ('fy',            'Frisian',                      'fy',             'Frisian'),
    ('ga',            'Irish',                        'ga',             'Irish'),
    ('gan-hant',      'gan-hant',                     'unknown',        'unknown'),
    ('gd',            'Gaelic (Scots)',               'gd',             'Gaelic (Scots)'),
    ('gd-ie',         'Gaelic (Irish)',               'gd',             'Gaelic (Scots)'),
    ('gl',            'Galacian',                     'gl',             'Galacian'),
    ('got',           'got',                          'unknown',        'unknown'),
    ('grc',           'grc',                          'unknown',        'unknown'),
    ('gsw',           'gsw',                          'unknown',        'unknown'),
    ('gu',            'Gujurati',                     'gu',             'Gujurati'),
    ('he',            'Hebrew',                       'he',             'Hebrew'),
    ('hif-deva',      'hif-deva',                     'unknown',        'unknown'),
    ('hi',            'Hindi',                        'hi',             'Hindi'),
    ('ho',            'ho',                           'unknown',        'unknown'),
    ('hr',            'Croatian',                     'hr',             'Croatian'),
    ('hsb',           'Upper Sorbian',                'hsb',            'Upper Sorbian'),
    ('ht',            'Haitian',                      'ht',             'Haitian'),
    ('hu',            'Hungarian',                    'hu',             'Hungarian'),
    ('hun',           'hun',                          'unknown',        'unknown'),
    ('hy',            'Armenian',                     'hy',             'Armenian'),
    ('hz',            'hz',                           'unknown',        'unknown'),
    ('ia',            'ia',                           'unknown',        'unknown'),
    ('id',            'Indonesian',                   'id',             'Indonesian'),
    ('ike-cans',      'ike-cans',                     'unknown',        'unknown'),
    ('ike-latn',      'ike-latn',                     'unknown',        'unknown'),
    ('io',            'io',                           'unknown',        'unknown'),
    ('is',            'Icelandic',                    'is',             'Icelandic'),
    ('it-ch',         'Italian (Switzerland)',        'it',             'Italian'),
    ('it',            'Italian',                      'it',             'Italian'),
    ('iu',            'Inuktitut',                    'iu',             'Inuktitut'),
    ('ja',            'Japanese',                     'ja',             'Japanese'),
    ('ji',            'Yiddish',                      'ji',             'Yiddish'),
    ('jv',            'jv',                           'unknown',        'unknown'),
    ('ka',            'Georgian',                     'ka',             'Georgian'),
    ('kk-arab',       'kk-arab',                      'unknown',        'unknown'),
    ('kk-cn',         'kk-cn',                        'unknown',        'unknown'),
    ('kk',            'Kazakh',                       'kk',             'Kazakh'),
    ('kk-latn',       'kk-latn',                      'unknown',        'unknown'),
    ('kl',            'kl',                           'unknown',        'unknown'),
    ('km',            'Khmer',                        'km',             'Khmer'),
    ('kn',            'Kannada',                      'kn',             'Kannada'),
    ('koi',           'koi',                          'unknown',        'unknown'),
    ('ko',            'Korean',                       'ko',             'Korean'),
    ('ko-kp',         'Korean (North Korea)',         'ko',             'Korean'),
    ('ko-kr',         'Korean (South Korea)',         'ko',             'Korean'),
    ('ksh',           'ksh',                          'unknown',        'unknown'),
    ('ks',            'Kashmiri',                     'ks',             'Kashmiri'),
    ('kv',            'kv',                           'unknown',        'unknown'),
    ('ky',            'Kirghiz',                      'ky',             'Kirghiz'),
    ('la',            'Latin',                        'la',             'Latin'),
    ('lb',            'Luxembourgish',                'lb',             'Luxembourgish'),
    ('lfn',           'lfn',                          'unknown',        'unknown'),
    ('lg',            'lg',                           'unknown',        'unknown'),
    ('li',            'li',                           'unknown',        'unknown'),
    ('lt',            'Lithuanian',                   'lt',             'Lithuanian'),
    ('lv',            'Latvian',                      'lv',             'Latvian'),
    ('lzz',           'lzz',                          'unknown',        'unknown'),
    ('mai',           'mai',                          'unknown',        'unknown'),
    ('map-bms',       'map-bms',                      'unknown',        'unknown'),
    ('mg',            'mg',                           'unknown',        'unknown'),
    ('mi',            'Maori',                        'mi',             'Maori'),
    ('min',           'min',                          'unknown',        'unknown'),
    ('mk',            'FYRO Macedonian',              'mk',             'FYRO Macedonian'),
    ('ml',            'Malayalam',                    'ml',             'Malayalam'),
    ('mn',            'Mongolian',                    'mn',             'Mongolian'),
    ('mo',            'Moldavian',                    'mo',             'Moldavian'),
    ('mr',            'Marathi',                      'mr',             'Marathi'),
    ('ms',            'Malay',                        'ms',             'Malay'),
    ('mt',            'Maltese',                      'mt',             'Maltese'),
    ('mul',           'mul',                          'unknown',        'unknown'),
    ('mu',            'mu',                           'unknown',        'unknown'),
    ('my',            'Burmese',                      'my',             'Burmese'),
    ('myv',           'myv',                          'unknown',        'unknown'),
    ('mzn',           'mzn',                          'unknown',        'unknown'),
    ('nb',            'Norwegian (Bokmal)',           'nb',             'Norwegian (Bokmal)'),
    ('nds-nl',        'nds-nl',                       'unknown',        'unknown'),
    ('ne',            'Nepali',                       'ne',             'Nepali'),
    ('new',           'new',                          'unknown',        'unknown'),
    ('ng',            'Ndonga',                       'ng',             'Ndonga'),
    ('nl-be',         'Dutch (Belgian)',              'nl',             'Dutch'),
    ('nl',            'Dutch',                        'nl',             'Dutch'),
    ('nn',            'Norwegian (Nynorsk)',          'nn',             'Norwegian (Nynorsk)'),
    ('no',            'Norwegian',                    'no',             'Norwegian'),
    ('nov',           'nov',                          'unknown',        'unknown'),
    ('nrm',           'nrm',                          'unknown',        'unknown'),
    ('nv',            'Navajo',                       'nv',             'Navajo'),
    ('oc',            'Occitan',                      'oc',             'Occitan'),
    ('om',            'Oromo',                        'om',             'Oromo'),
    ('or',            'Oriya',                        'or',             'Oriya'),
    ('pa-in',         'Punjabi (India)',              'pa',             'Punjabi'),
    ('pam',           'pam',                          'unknown',        'unknown'),
    ('pa-pk',         'Punjabi (Pakistan)',           'pa',             'Punjabi'),
    ('pa',            'Punjabi',                      'pa',             'Punjabi'),
    ('pie',           'pie',                          'unknown',        'unknown'),
    ('pl2',           'pl2',                          'unknown',        'unknown'),
    ('pl',            'Polish',                       'pl',             'Polish'),
    ('pms',           'pms',                          'unknown',        'unknown'),
    ('pnb',           'pnb',                          'unknown',        'unknown'),
    ('ps',            'ps',                           'unknown',        'unknown'),
    ('pt-br',         'Portuguese (Brazil)',          'pt',             'Portuguese'),
    ('pt',            'Portuguese',                   'pt',             'Portuguese'),
    ('qu',            'Quechua',                      'qu',             'Quechua'),
    ('rm',            'Rhaeto-Romanic',               'rm',             'Rhaeto-Romanic'),
    ('rmy',           'rmy',                          'unknown',        'unknown'),
    ('roa-rup',       'roa-rup',                      'unknown',        'unknown'),
    ('ro-mo',         'Romanian (Moldavia)',          'ro',             'Romanian'),
    ('ro',            'Romanian',                     'ro',             'Romanian'),
    ('rue',           'rue',                          'unknown',        'unknown'),
    ('ru-mo',         'Russian (Moldavia)',           'ru',             'Russian'),
    ('ru',            'Russian',                      'ru',             'Russian'),
    ('rw',            'rw',                           'unknown',        'unknown'),
    ('sah',           'sah',                          'unknown',        'unknown'),
    ('sa',            'Sanskrit',                     'sa',             'Sanskrit'),
    ('sb',            'Sorbian',                      'sb',             'Sorbian'),
    ('sco',           'sco',                          'unknown',        'unknown'),
    ('sc',            'Sardinian',                    'sc',             'Sardinian'),
    ('sd',            'Sindhi',                       'sd',             'Sindhi'),
    ('sei',           'sei',                          'unknown',        'unknown'),
    ('sg',            'Sango',                        'sg',             'Sango'),
    ('sh',            'Serbo-Croatian',               'sh',             'Serbo-Croatian'),
    ('simple',        'simple',                       'unknown',        'unknown'),
    ('si',            'Singhalese',                   'si',             'Singhalese'),
    ('sk',            'Slovak',                       'sk',             'Slovak'),
    ('sl',            'Slovenian',                    'sl',             'Slovenian'),
    ('sm',            'sm',                           'unknown',        'unknown'),
    ('so',            'Somani',                       'so',             'Somani'),
    ('sq',            'Albanian',                     'sq',             'Albanian'),
    ('sr-ec',         'sr-ec',                        'unknown',        'unknown'),
    ('sr-el',         'sr-el',                        'unknown',        'unknown'),
    ('sr-la',         'Serbian (Latin)',              'sr',             'Serbian'),
    ('sr',            'Serbian',                      'sr',             'Serbian'),
    ('sr-zb',         'sr-zb',                        'unknown',        'unknown'),
    ('ss',            'ss',                           'unknown',        'unknown'),
    ('stq',           'stq',                          'unknown',        'unknown'),
    ('su',            'su',                           'unknown',        'unknown'),
    ('sv-fi',         'Swedish (Finland)',            'sv',             'Swedish'),
    ('sv-sv',         'Swedish (Sweden)',             'sv',             'Swedish'),
    ('sv',            'Swedish',                      'sv',             'Swedish'),
    ('sw',            'Swahili',                      'sw',             'Swahili'),
    ('sx',            'Sutu',                         'sx',             'Sutu'),
    ('szl',           'szl',                          'unknown',        'unknown'),
    ('sz',            'Sami (Lappish)',               'sz',             'Sami (Lappish)'),
    ('ta',            'Tamil',                        'ta',             'Tamil'),
    ('tcy',           'tcy',                          'unknown',        'unknown'),
    ('te',            'Teluga',                       'te',             'Teluga'),
    ('tet',           'tet',                          'unknown',        'unknown'),
    ('tg',            'tg',                           'unknown',        'unknown'),
    ('th',            'Thai',                         'th',             'Thai'),
    ('tig',           'Tigre',                        'tig',            'Tigre'),
    ('tk',            'Turkmen',                      'tk',             'Turkmen'),
    ('tlh',           'Klingon',                      'tlh',            'Klingon'),
    ('tl',            'Tagalog',                      'tl',             'Tagalog'),
    ('tn',            'Tswana',                       'tn',             'Tswana'),
    ('to',            'to',                           'unknown',        'unknown'),
    ('tr',            'Turkish',                      'tr',             'Turkish'),
    ('ts',            'Tsonga',                       'ts',             'Tsonga'),
    ('tt-cyrl',       'tt-cyrl',                      'unknown',        'unknown'),
    ('tt',            'Tatar',                        'tt',             'Tatar'),
    ('tw',            'tw',                           'unknown',        'unknown'),
    ('udm',           'udm',                          'unknown',        'unknown'),
    ('ug-latn',       'ug-latn',                      'unknown',        'unknown'),
    ('uk',            'Ukrainian',                    'uk',             'Ukrainian'),
    ('ur',            'Urdu',                         'ur',             'Urdu'),
    ('uz',            'uz',                           'unknown',        'unknown'),
    ('val',           'val',                          'unknown',        'unknown'),
    ('vec',           'vec',                          'unknown',        'unknown'),
    ('ve',            'Venda',                        've',             'Venda'),
    ('vi',            'Vietnamese',                   'vi',             'Vietnamese'),
    ('vo',            'Volapuk',                      'vo',             'Volapuk'),
    ('wa',            'Walloon',                      'wa',             'Walloon'),
    ('wuu',           'wuu',                          'unknown',        'unknown'),
    ('xh',            'Xhosa',                        'xh',             'Xhosa'),
    ('xmf',           'xmf',                          'unknown',        'unknown'),
    ('yi',            'yi',                           'unknown',        'unknown'),
    ('yue',           'yue',                          'unknown',        'unknown'),
    ('za',            'za',                           'unknown',        'unknown'),
    ('zh',            'Chinese',                      'zh',             'Chinese'),
    ('zh-class',      'zh-class',                     'unknown',        'unknown'),
    ('zh-clas',       'zh-clas',                      'unknown',        'unknown'),
    ('zh-cn',         'Chinese (PRC)',                'zh',             'Chinese'),
    ('zh-hans',       'zh-hans',                      'unknown',        'unknown'),
    ('zh-hant',       'zh-hant',                      'unknown',        'unknown'),
    ('zh-hk',         'Chinese (Hong Kong)',          'zh',             'Chinese'),
    ('zh-min-n',      'zh-min-n',                     'unknown',        'unknown'),
    ('zh-mo',         'zh-mo',                        'unknown',        'unknown'),
    ('zho',           'zho',                          'unknown',        'unknown'),
    ('zh-sg',         'Chinese (Singapore)',          'zh',             'Chinese'),
    ('zh-tw',         'Chinese (Taiwan)',             'zh',             'Chinese'),
    ('zh-yue',        'zh-yue',                       'unknown',        'unknown'),
    ('zu',            'Zulu',                         'zu',             'Zulu')
;

COMMIT;

