DROP TABLE IF EXISTS statsdb.lookup_language_codes;

CREATE TABLE statsdb.lookup_language_codes (
    language_code    VARCHAR(5) NOT NULL,
    language_name    VARCHAR(255),
    PRIMARY KEY (language_code),
    UNIQUE KEY (language_name)
) ENGINE=InnoDB;

INSERT INTO statsdb.lookup_language_codes VALUES 
    ('af',      'Afrikaans'),
    ('ar',      'Arabic'),
    ('bg',      'Bulgarian'),
    ('bn',      'Bengali/Bangla'),
    ('bs',      'Bosnian'),
    ('ca',      'Catalan'),
    ('cs',      'Czech'),
    ('cy',      'Welsh'),
    ('da',      'Danish'),
    ('de',      'German'),
    ('el',      'Greek'),
    ('en-au',   'English (Australia)'),
    ('en-ca',   'English (Canadian)'),
    ('en',      'English'),
    ('en-gb',   'English (United Kingdom)'),
    ('eo',      'Esperanto'),
    ('es',      'Spanish'),
    ('et',      'Estonian'),
    ('eu',      'Basque'),
    ('fa',      'Persian'),
    ('fi',      'Finnish'),
    ('fo',      'Faroese'),
    ('fr-ca',   'French (Canada)'),
    ('fr',      'French'),
    ('gl',      'Galician'),
    ('gu',      'Gujarati'),
    ('he',      'Hebrew'),
    ('hi',      'Hindi'),
    ('hr',      'Croatian'),
    ('hu',      'Hungarian'),
    ('is',      'Icelandic'),
    ('it',      'Italian'),
    ('ja',      'Japanese'),
    ('ka',      'Georgian'),
    ('km',      'Khmer'),
    ('ko',      'Korean'),
    ('lt',      'Lithuanian'),
    ('lv',      'Latvian'),
    ('mn',      'Mongolian'),
    ('ms',      'Malay'),
    ('nb',      'Norwegian Bokmal'),
    ('nl',      'Dutch'),
    ('no',      'Norwegian'),
    ('pl',      'Polish'),
    ('pt-br',   'Portuguese (Brazil)'),
    ('pt',      'Portuguese (Portugal)'),
    ('ro',      'Romanian'),
    ('ru',      'Russian'),
    ('sk',      'Slovak'),
    ('sl',      'Slovenian'),
    ('sr-latn', 'Serbian (Latin)'),
    ('sr',      'Serbian (Cyrillic)'),
    ('sv',      'Swedish'),
    ('th',      'Thai'),
    ('tr',      'Turkish'),
    ('uk',      'Ukrainian'),
    ('vi',      'Vietnamese'),
    ('zh',      'Chinese Traditional'),
    ('zh-cn',   'Chinese Simplified')
;

COMMIT;

