/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PhalanxRecord extends org.jooq.impl.UpdatableRecordImpl<com.wikia.phalanx.db.tables.records.PhalanxRecord> {

	private static final long serialVersionUID = 1449395717;

	/**
	 * The table column <code>phalanx.phalanx.p_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setPId(org.jooq.tools.unsigned.UInteger value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_ID, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_id</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public org.jooq.tools.unsigned.UInteger getPId() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_ID);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_author_id</code>
	 */
	public void setPAuthorId(java.lang.Integer value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_AUTHOR_ID, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_author_id</code>
	 */
	public java.lang.Integer getPAuthorId() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_AUTHOR_ID);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_text</code>
	 */
	public void setPText(byte[] value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TEXT, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_text</code>
	 */
	public byte[] getPText() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TEXT);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_ip_hex</code>
	 */
	public void setPIpHex(java.lang.String value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_IP_HEX, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_ip_hex</code>
	 */
	public java.lang.String getPIpHex() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_IP_HEX);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_type</code>
	 */
	public void setPType(org.jooq.tools.unsigned.UShort value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TYPE, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_type</code>
	 */
	public org.jooq.tools.unsigned.UShort getPType() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TYPE);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_timestamp</code>
	 */
	public void setPTimestamp(byte[] value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TIMESTAMP, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_timestamp</code>
	 */
	public byte[] getPTimestamp() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_TIMESTAMP);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_expire</code>
	 */
	public void setPExpire(byte[] value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_EXPIRE, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_expire</code>
	 */
	public byte[] getPExpire() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_EXPIRE);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_exact</code>
	 */
	public void setPExact(java.lang.Byte value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_EXACT, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_exact</code>
	 */
	public java.lang.Byte getPExact() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_EXACT);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_regex</code>
	 */
	public void setPRegex(java.lang.Byte value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_REGEX, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_regex</code>
	 */
	public java.lang.Byte getPRegex() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_REGEX);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_case</code>
	 */
	public void setPCase(java.lang.Byte value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_CASE, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_case</code>
	 */
	public java.lang.Byte getPCase() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_CASE);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_reason</code>
	 */
	public void setPReason(byte[] value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_REASON, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_reason</code>
	 */
	public byte[] getPReason() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_REASON);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_lang</code>
	 */
	public void setPLang(java.lang.String value) {
		setValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_LANG, value);
	}

	/**
	 * The table column <code>phalanx.phalanx.p_lang</code>
	 */
	public java.lang.String getPLang() {
		return getValue(com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_LANG);
	}

	/**
	 * Create a detached PhalanxRecord
	 */
	public PhalanxRecord() {
		super(com.wikia.phalanx.db.tables.Phalanx.PHALANX);
	}
}
