/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class PhalanxStatsRecord extends org.jooq.impl.TableRecordImpl<com.wikia.phalanx.db.tables.records.PhalanxStatsRecord> {

	private static final long serialVersionUID = 910031294;

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_id</code>
	 */
	public void setPsBlockerId(org.jooq.tools.unsigned.UInteger value) {
		setValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKER_ID, value);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_id</code>
	 */
	public org.jooq.tools.unsigned.UInteger getPsBlockerId() {
		return getValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKER_ID);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_type</code>
	 */
	public void setPsBlockerType(org.jooq.tools.unsigned.UShort value) {
		setValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKER_TYPE, value);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocker_type</code>
	 */
	public org.jooq.tools.unsigned.UShort getPsBlockerType() {
		return getValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKER_TYPE);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_timestamp</code>
	 */
	public void setPsTimestamp(byte[] value) {
		setValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_TIMESTAMP, value);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_timestamp</code>
	 */
	public byte[] getPsTimestamp() {
		return getValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_TIMESTAMP);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocked_user</code>
	 */
	public void setPsBlockedUser(java.lang.String value) {
		setValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKED_USER, value);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_blocked_user</code>
	 */
	public java.lang.String getPsBlockedUser() {
		return getValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_BLOCKED_USER);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_wiki_id</code>
	 */
	public void setPsWikiId(java.lang.Integer value) {
		setValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_WIKI_ID, value);
	}

	/**
	 * The table column <code>phalanx.phalanx_stats.ps_wiki_id</code>
	 */
	public java.lang.Integer getPsWikiId() {
		return getValue(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS.PS_WIKI_ID);
	}

	/**
	 * Create a detached PhalanxStatsRecord
	 */
	public PhalanxStatsRecord() {
		super(com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS);
	}
}
