/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>phalanx</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Keys {

	// IDENTITY definitions
	public static final org.jooq.Identity<com.wikia.phalanx.db.tables.records.PhalanxRecord, org.jooq.tools.unsigned.UInteger> IDENTITY_PHALANX = Identities0.IDENTITY_PHALANX;

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<com.wikia.phalanx.db.tables.records.PhalanxRecord> KEY_PHALANX_PRIMARY = UniqueKeys0.KEY_PHALANX_PRIMARY;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings("hiding")
	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.wikia.phalanx.db.tables.records.PhalanxRecord, org.jooq.tools.unsigned.UInteger> IDENTITY_PHALANX = createIdentity(com.wikia.phalanx.db.tables.Phalanx.PHALANX, com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_ID);
	}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.wikia.phalanx.db.tables.records.PhalanxRecord> KEY_PHALANX_PRIMARY = createUniqueKey(com.wikia.phalanx.db.tables.Phalanx.PHALANX, com.wikia.phalanx.db.tables.Phalanx.PHALANX.P_ID);
	}
}
