/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Phalanx extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1725267633;

	/**
	 * The singleton instance of phalanx
	 */
	public static final Phalanx PHALANX = new Phalanx();

	/**
	 * No further instances allowed
	 */
	private Phalanx() {
		super("wikicities");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.wikia.phalanx.db.tables.Phalanx.PHALANX,
			com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS);
	}
}
