/**
 * This class is generated by jOOQ
 */
package com.wikia.phalanx.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in phalanx
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * The table phalanx.phalanx
	 */
	public static final com.wikia.phalanx.db.tables.Phalanx PHALANX = com.wikia.phalanx.db.tables.Phalanx.PHALANX;

	/**
	 * The table phalanx.phalanx_stats
	 */
	public static final com.wikia.phalanx.db.tables.PhalanxStats PHALANX_STATS = com.wikia.phalanx.db.tables.PhalanxStats.PHALANX_STATS;

	/**
	 * No instances
	 */
	private Tables() {}
}
