CREATE TABLE statsdb.rollup_wiki_all_events (
    period_id                   SMALLINT UNSIGNED NOT NULL,
    time_id                     DATETIME NOT NULL,
    wiki_id                     INTEGER UNSIGNED NOT NULL,
    main_creates                INTEGER UNSIGNED,
    main_edits                  INTEGER UNSIGNED,
    main_deletes                INTEGER UNSIGNED,
    main_undeletes              INTEGER UNSIGNED,
    template_creates            INTEGER UNSIGNED,
    template_edits              INTEGER UNSIGNED,
    template_deletes            INTEGER UNSIGNED,
    template_undeletes          INTEGER UNSIGNED,
    file_creates                INTEGER UNSIGNED,
    file_edits                  INTEGER UNSIGNED,
    file_deletes                INTEGER UNSIGNED,
    file_undeletes              INTEGER UNSIGNED,
    user_talk_creates           INTEGER UNSIGNED,
    user_talk_edits             INTEGER UNSIGNED,
    user_talk_deletes           INTEGER UNSIGNED,
    user_talk_undeletes         INTEGER UNSIGNED,
    talk_creates                INTEGER UNSIGNED,
    talk_edits                  INTEGER UNSIGNED,
    talk_deletes                INTEGER UNSIGNED,
    talk_undeletes              INTEGER UNSIGNED,
    user_creates                INTEGER UNSIGNED,
    user_edits                  INTEGER UNSIGNED,
    user_deletes                INTEGER UNSIGNED,
    user_undeletes              INTEGER UNSIGNED,
    category_creates            INTEGER UNSIGNED,
    category_edits              INTEGER UNSIGNED,
    category_deletes            INTEGER UNSIGNED,
    category_undeletes          INTEGER UNSIGNED,
    blog_article_talk_creates   INTEGER UNSIGNED,
    blog_article_talk_edits     INTEGER UNSIGNED,
    blog_article_talk_deletes   INTEGER UNSIGNED,
    blog_article_talk_undeletes INTEGER UNSIGNED,
    project_creates             INTEGER UNSIGNED,
    project_edits               INTEGER UNSIGNED,
    project_deletes             INTEGER UNSIGNED,
    project_undeletes           INTEGER UNSIGNED,
    mediawiki_main_creates      INTEGER UNSIGNED,
    mediawiki_main_edits        INTEGER UNSIGNED,
    mediawiki_main_deletes      INTEGER UNSIGNED,
    mediawiki_main_undeletes    INTEGER UNSIGNED,
    PRIMARY KEY (period_id, time_id, wiki_id),
    INDEX (wiki_id, period_id, time_id)
) ENGINE=InnoDB
  PARTITION BY RANGE COLUMNS(time_id) (
    PARTITION p0 VALUES LESS THAN ('1970-01-01')
)

